# 2.1 Getting started

We'll be using Jupyter Lab as our preferred __development environment__ for class. However, remember that everything inside Jupyter Lab is just a module, and there are independent apps and other development environments that can do the job of any one module just as well or better. For example, some times its easiest to do some quick computations right from a regular __terminal__. Also, Jupyter Lab is only in "alpha," which means that its still in an early phase of development so its features are constantly changing and are not fully implemented.

Open a __terminal__ window. The default __shell__ is likely to be "bash" or the "Bourne" shell. Type "__python__." This will start the python command line intepreter in the terminal window and will inform you of a helpful command/__function__: __help()__. The prompt __>>>__ means python is ready for input. Read chapter 2 in the textbook and tryout someof the basic commands.

# 2.2 Basic Programming

A program is list of __statements__, i.e. instructions, __executed__ by a computer.

## 2.2.1 Variables and Assignments and 2.2.2 Variable Types

Here are some __variable types__ and some __assigment statements__
   - integer x=1, x = 1, x=int(1.0) (spaces are OK - good for readability, but not OK at beginning of statements)
   - float e.g. x = 1.2e34, x=float(1)
   - complex e.g. x = 1 + 2j, x=complex(1.5)
   - string x="this is a string",x="1.234"
      
Variable names cannot start with number, contain symbols or spaces, cannot be reserved word, and are case sensitive.          
## 2.2.3 Output and Input Statements
output statements
   - print() (note: python 2 doesn't have parentheses) 
   - print will do some autoformating that can be helpful or annoying as in the example below 

In [2]:
x=1
y=2
ystr=str(y)
print(x)
print(ystr)
print(ystr.strip())
print("The value of x is",x,"and the value of y is",ystr.strip(),".")
z=3
print(x,y,z,sep="&")
print(x,y,z,sep=" & ")

1
2
2
The value of x is 1 and the value of y is 2 .
1&2&3
1 & 2 & 3


Input is accomplishe with __input()__. Input() interprets all input as a string, which complicates its use.

In [ ]:
temp=input("Enter the value of x: ")

In [4]:
print("The value of x is:",temp)
print("The value of x/3 is:", temp/3)

The value of x is: 10


TypeError: unsupported operand type(s) for /: 'str' and 'int'

This works better:

In [ ]:
x=int(temp)
print("The value of x is:",x)
print("The value of x/3 is:", x/3)

Here's another version:

In [25]:
x=float(input("Enter the value of x: "))

## 2.2.4 Arithmetic

### Basic Arithmetic

- addition: x+y
- subtraction: x-y
- multiplication: x*y
- division: x/y # This always returns a float!
- powers: x**y
- integer division: x//y
- modulo: x%y

Regular division will never give an integer result. Otherwise, results are the most general variable type of input variables. Order of operation follows regular algebra.


### More Obscrure Arithmetic

- bitwise OR: x/y
- bitwise AND: x&y
- bitwise XOR: x^y
- shifting integer bits x rightwards y places: x>>y
- shifting integer bits x leftwards y places: x<<y

### Python Modifiers

These eliminate the need to write assignment statements that look like bad algebra.

- x += 1
- x -= 4
- x *= -2.6
- x /= 5*y
- x //= 4.4

### Assigning multiple variables in a single statement

The key here is to remember that python will evaluate the expressins on the right first, and them assign them to the variables on the left.

x,y = 2*z+1, (x+y)/3 

x, y = y, x



## 2.2.5 Functions, Packages, and Modules

Here are some __packages__ that contain key __functions__ and variables. Some packages have __modules__.

 - math
 - numpy
 - pylab
 
Because astronomy invovles numbers thatn involve huge orders of magnitude, astronomy related packages often have versions of funtions that are better suited for astronomy (surprise!). If there are packags desdigned to address your specific problem exist, try to use those.

Since different packages may have functions with the same name, its best to import each function or variable you want to use explicitly from your package of choice.

In [ ]:
from pylab import plot, show, ylim

from pylab import ylim, xlabel, ylabel

from numpy import linspace, sin, cos

from numpy import loadtxt

## 2.2.6 BuiltIn Functions

abs()

## 2.2.7 Comment Statements


In [29]:
# This is a comment
print("Python ignores anything that follows a #.") # another comment

Python ignores anything that follows a #.


# 2.3 Controlling Programs with "if" and "while"

## 2.3.2 The "if" statement

The indentations in the if statment are necessary! One is enough but four spaces is standard practice.

In [31]:
x = int(input("Enter a whole number no grater than ten: "))
if x>10:
    print("You entered a value greater than ten!")
    print("I shall fix that...")
    x = 10
print("your number is", x)    

You entered a value greater than ten!
I shall fix that...
your number is 10


Here are some __condition__ statements:
```
if x == 1:
if x > 1:
if x >= 1:
if x < 1:
if x <= 1:
if x != 1:
if x > 10 or x <1:
if x<= 10 and x>= 1: # can combine multiple conditions with and/or
elif x>9: # there can be as many of these as you like
else:
```

## 2.3.2 The `while` Statement

This is just a variation of the `if` statement, with the possibility of entering and infinite loop. Close the windown in which the prgram is running to exit. In Jupyter Lab, you can kill the kernel in which it is running under the Running tab.

There is an option for an `else` statement which will be executed once and only once when the condition for the `while` statement fails.

Here's a nifty little program:

In [33]:
f1, f2, maxf1 = 1, 1, 500
while f1<= maxf1:
    print(f1)
    f1, f2 = f2, f1+f2
else: print("You've generated the Fibonacci sequence up to", maxf1,"!")

1
1
2
3
5
8
13
21
34
55
89
144
233
377
You've generated the Fibonacci sequence up to 500 !


## 2.3.3 `break` and `continue`

`break` forces an exit out of the `while` statement

`continue` skips the rest of the while statement and goes back to the beginng of the `while` statement and re-evaluates the condition.

# 2.4 Lists and Arrays

__Containers__ are collections of numbers.

## 2.4.1 Lists

A variable can be a list, and a list can contain __elements__ of different types. It can even be empty.

In [51]:
r = [1,2,3,4,5.0,6+4.5j]
x, y, z = 1,2,3
r=[x,y,z]
r = [2*x, x+y, z/sqrt(x**2+y**2)]
r=[]

Note below that reference to the elements starts with `[0]`

In [37]:
from math import sqrt
r = [1.0,1.5,-2.2]
length = sqrt(r[0]**2+r[1]**2+r[2]**2)
print(length)

2.8442925306655784


There are built in functions that operate on entire lists at once:

In [41]:
total = sum(r)
rmax = max(r)
rmin = min(r)
n_r = len(r)
print(total, rmax, rmin, n_r, total/n_r)

0.2999999999999998 1.5 -2.2 3 0.09999999999999994


Python can apply a function to whole list through the special function __`map`__. The resulting __object__, called an __iterator__, can be assigned to a list variable.

In [47]:
from math import log
r = [1.0,1.5,-2.2]
r_n =list(map(abs,r)) # log will only take positive numbers
logr = list(map(log,r_n)) 
print(r)
print(logr)

[1.0, 1.5, -2.2]
[0.0, 0.4054651081081644, 0.7884573603642703]


It's possible to add or remove elements from lists

In [48]:
r.append(6.1)
print(r)
r.pop()
print(r)
r.pop(1)
print(r)

[1.0, 1.5, -2.2, 6.1]
[1.0, 1.5, -2.2]
[1.0, -2.2]


## 2.4.2 Arrays

Arrays have a fixed number of elements of the same variable type. They can be multi-dimentional and behave mathematically like like vectors and matrices. They also work faster than lists.

Here are some ways to create them:

In [58]:
from numpy import zeros, empty, array
a = empty(4, float)
print(a)
a = zeros([3,4], float)
print(a)
row1 = [1,2,3]
row2 = [3,4,5]
a = array([row1,row2])
print(a)
print(a[0,1]) # note the row first column second convention
print(a[1,2])

[  3.10503618e+231  -4.33385699e-311   2.14689531e-314   2.78134232e-309]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[1 2 3]
 [3 4 5]]
2
5


## 2.4.3 Reading an Array from a File

In principle, the following can also work for a two dimentional array.

In [69]:
from numpy import loadtxt
data = loadtxt("./cpresources/velocities.txt", float)
print(len(data))

101


## 2.4.4 Arithmetic with Arrays

In general, arithmetic operations are applied independently to each element of the array or arrays.

In [70]:
a=array([1,2,3,4],int)
b=array([2,4,6,8],int)
print(a*b)
print(a*(2*b))

[ 2  8 18 32]
[ 4 16 36 64]


For vector or matric products use `dot`

In [71]:
from numpy import dot
print(dot(a,b))

60


Functions that apply to lists can also be used for one-dimentional arrays. However, the `numpy` package contains functions that work for arrays of all dimentions.

In [74]:
c = array([a,b])
print(c.size)
print(c.shape) # the result of this is technically called a "tuple" but it works like a list

8
(2, 4)


### CAUTION Renaming Arrays vs Assigning the values of an Array to a New Array

In [75]:
from numpy import array
a = array ([1,1],int)
b = a
a[0] = 2
print(a)
print(b)

[2 1]
[2 1]


The example above shows that if `a` is an array `b=a` just creates a new alias, i.e. new name, for the array `a`. To copy an array the function `copy` from the `numpy` package is necessary.

## 2.4.5 Slicing

Get a subset of a list or array:

In [77]:
sub = c[1,:]
print(sub)

[2 4 6 8]


# 2.5 For Loops

In Python, the default for for loops, `for n in r`, goes through each element of a list or array. It will also take `break` and `continue` statments.

In [79]:
r = [1,3,5]
for n in r:
    print(n)
    print(2*n)
print("Finished!")

1
2
3
6
5
10
Finished!


Python has a built-in function to generate a list (technically an iterator) of numbers. If there is only one arguent, it will generate n numbers ranging from 0 to n-1. When given two arguments, it will generate a list starting from the first number, and ending before the last number, in incremetns of 1. A third argument specifies the spacing. (The iterator can be turned into a list using `list(range(n))`. This is necessary to print what `range` generates.)

In [81]:
for n in range(5):
    print(n**2)

0
1
4
9
16


In [86]:
print(list(range(2,8)))

[2, 3, 4, 5, 6, 7]


In [85]:
print(list(range(20,2,-3)))

[20, 17, 14, 11, 8, 5]


`numpy` has some other handy functions `arange()` and `linspace()` `arange` generates actual arrays, both integer and floating point, equivalent to range. `linspace` will generate a floating point array with a given number of elements within given limits.

In [92]:
from numpy import arange, linspace
print(arange(1.0,8.0,2.0))

[ 1.  3.  5.  7.]


In [93]:
print(linspace(2.0, 2.8, 3))

[ 2.   2.4  2.8]


### Example 2.6 Performing a Sum

In [98]:
data = loadtxt("./cpresources/velocities.txt", float)
print(data.shape)
s = empty(2, float)# create variable
print(s)
for x in data:
    s += x**2
print(s)

(101, 2)
[  6.76700000e+05   5.28484584e+01]
[  1.01505000e+06   7.92726875e+01]
202
(101, 2)


Create some data and plot it. Once the plot is generated as an object, then you need to `show()` it.

### Example 2.7 Emission Lines of Hydrogen

In [99]:
R=1.097e-2
for m in range(1,4):
    print('Series for m =', m)
    for n in range(m+1,m+6):
        invlambda = R*(1/m**2 - 1/n**2)
        print("   ", 1/invlambda,' nm')

Series for m = 1
    121.5436037678517  nm
    102.55241567912488  nm
    97.23488301428137  nm
    94.95594044363415  nm
    93.76220862091418  nm
Series for m = 2
    656.3354603463993  nm
    486.1744150714068  nm
    434.084299170899  nm
    410.2096627164995  nm
    397.04243897498225  nm
Series for m = 3
    1875.2441724182836  nm
    1281.9051959890612  nm
    1093.8924339106654  nm
    1005.013673655424  nm
    954.6697605038536  nm


# User-Defined Functions

Let's define a function. Remember that variables defined within a function are __local variables__ that only exists within the function.

In [103]:
def factorial(n):
    f=1.0
    for k in range(1,n+1):
        f *= k
    return f

Now let's use it.

In [104]:
print(factorial(10))

3628800.0


Note that functions can have multiple inputs and nultiple or no output. For good form , functions are typically placed at the beginning of a program. However, they can be place in a separate `.py` file and imported like any other Python function.

### Example 2.8 Prime Numbers

In [108]:
def factors(n):
    factorlist = [] # create an empty list
    k=2 # start with two
    while k<=n:
        while n%k==0: # if there is no remainder, it is a factor
            factorlist.append(k) # add it to the factorlist
            n //= k # now we just need to find the factors of n/k which we make the new n, but an integer
        k += 1 # increment k
    return factorlist

# 2.7 Good Programming Style

1. Include comments
2. Use meaningful variable names
3. Use the right type of variables
44. Import functions first
5. Give your constants names
6. Use user-fefine functions where appropriate
7. Print out partia res7ults and updates throughout your program
8. Lay out your program clearly
9. Dont't make your program unnecessarily complicated
